### ISSUE TITLE
Date in statusbar duplicates

### ISSUE THREAD

**Issue by func0der** [GravityBox/GravityBox#1242]
Hey there,

I have a problem with the date showing in the status bar.
No matter how I configure it, it just duplicates sometimes.

I only found one reliable way to reproduce this.
1. Use Cyanogenmod with Theme Engine (Newest 10.2) should be the newest at this point).
2. Download any theme. I have Gem Flat, but I guess this does not matter.
3. Go to Settings and Theme and change for example the Font to that of another theme.
4. The date should have duplicated in the status bar. If you have configured the date to be smaller, then only the first of the X dates is small. The rest are big.

I guess this is some joining error in the date string.
If I disable date showinf in the status bar ehile the date is already multiplied ALL of them are going away.

I would be happay to help out with anything you need to fix this. Just say which log you may need and how to get it :)

func0der

**Comment by C3C0** [comment]
Hi.

Please note, GravityBox should not be used on custom ROMs like CyanogenMod. Refer to the compatibility info in the official support thread at XDA http://forum.xda-developers.com/xposed/modules/app-gravitybox-v3-1-4-tweak-box-android-t2316070
If you decide to use it, anyway, note that there's a master switch for clock settings which was implemented, due to the pressure from the users running GB on a custom ROMs, which can be used to disable clock tweaks that come from GravityBox to avoid conflicts with the custom ROM. Thanks for understanding.

C.

**Comment by func0der** [comment]
Since CM is the closest "close-to-vanilla" rom that I know, I do not understand this quiet.
Also Cyanogenmod does not have any possibility to add a date in the status bar, so there should be no hasseling there. I guess this is because of your on-the-fly behaviour which prepares stuff to be there already on boot or better "launcher init" (if that is a thing). This would explain why it happens after changing the theme. Because then the Launcher restarts or re-inits itself somehow and the behaviours get triggered again.

But since this is your module I can do nothing more than report the bug. The rest is up to you to decide.
But maybe there is a chance to build in a switch to make the above described behaviour optional. So people like me could make changes on-the-fly and disable that feature afterwards, so that changes may only be applied on reboot.
Everything else is working fine for me though.
