### ISSUE TITLE
There's a Bug in Screen Recording Feature

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1347]
Hell there  Devs,

When I try to record the screen with the GravityBox binary (by unchecking "use stock binary"), it fails to record (in a split second from hitting the record button, it shows a toast note that the recording is in the gallery. The recording  in the gallery, of course, can't be played and it's a broken file) AND it busts the whole sound on the phone. Media sound doesn't work in any app until I restart the phone.

**INFO**
Phone: Nexus 5
Android: 4.4.4
GravityBox: 3.5.9
Using Stock binary works.

**Comment by C3C0** [comment]
What settings exactly?

**Comment by ghost** [comment]
![_20150530_180742](https://cloud.githubusercontent.com/assets/8726042/7897882/d2329bbc-06f6-11e5-8509-d5e23e807124.JPG)

**Comment by C3C0** [comment]
Settings seem OK. 
Strange that it always worked OK for me when I was on KitKat (currently on LP 5.1 so I'm not able to test myself). There haven't been any changes to functionality since custom binary was introduced.
I need to see a logcat taken when screen recording starts to be able to tell more.
Also I recommend deleting screenrecord binary from /data/data/com.ceco.kitkat.gravitybox/files/screenrecord and reboot. New binary will be created after boot. To make sure the one that's there is the correct one.

**Comment by ghost** [comment]
Nope still didn't work.

But honestly, now that I think about it, I never really even used audio, nor have I ever exceeded 3 minutes.
I guess I just used that custom binary in the past because it's not the stock one.

I think the stock one isn't very bad, lol.

So really, just ignore this issue.
Focus on more recent versions, and good luck.
