### ISSUE TITLE
Ultimate notification control and progress-like notification = notification overload

### ISSUE THREAD

**Issue by eyalzek** [GravityBox/GravityBox#1413]
My device is Moto x 2014 on on android 5.1, I'm using xposed framework version 75 and GravityBox 5.3.3.
By default my phone vibrate twice for every notification I receive, that can become quite overwhelming when having a long conversation on whatsapp for example. I use the ultimate notification control for specific apps (whatsapp in this case) so that the device would only vibrate once for every notification, generally this works really well, unless it is a progress like notification. For example;
when sending someone a video on whatsapp, it creates a persistent progress bar notification to let you know how long it's going to take. What happens is, for every update of the percentage (so about a 100 times in a 30 sec interval) I'm getting a notification, both the vibration and the ringtone. It's quite intense and I have to put my phone on silent until the video is transferred.
In addition I also have "Alert only once" setting turned on which usually works well, but in this case it doesn't.

Maybe there should be some kind of filter for notification types if that's even possible?

**Comment by C3C0** [comment]
If it's a persistent notification (non-clearable) and you would like to avoid such behavior, make sure you uncheck "Ongoing" option if you have it checked. If you have it unchecked and behavior still persists,
then it's a non-standard implementation in said app as all progress notifications should typically be persistent having action buttons for cancellation purposes. There is nothing GB can do about it since it doesn't (and can't) know anything about notification context - what kind of notification it is and how it should be treated. The only "flag" that makes distinction is whether notification is persistent or not.

**Comment by eyalzek** [comment]
"Ongoing" option is unchecked...
So nothing can be done?

**Comment by C3C0** [comment]
The following commits should take care of such cases.
https://github.com/GravityBox/GravityBox/commit/6c45c97250f80d80663c08eae112738a2bc43fa4
https://github.com/GravityBox/GravityBox/commit/e95e3759b7bf59695ed7a498503c4522183cfc25
