### ISSUE TITLE
Cannot change battery type in status bar

### ISSUE THREAD

**Issue by roughnecks** [GravityBox/GravityBox#1446]
Hi there,
I've just installed xposed (stable version) along with GravityBox.

I managed to apply some changes in locker screen but others do not work; the one I was really interested in is the battery percentage on status bar, instead of default battery icon which is meaningless.

I tried different settings about battery but none of them seems to work (nothing changes in the status bar); I also tried rebooting - even if it's not requested - but I'm stuck.

I'm working on a cheap Woo tablet:

![screenshot_2016-01-12-23-16-25](https://cloud.githubusercontent.com/assets/1666536/12278697/b5ce46e4-b982-11e5-8446-18398e76fa18.png)
![screenshot_2016-01-12-23-16-34](https://cloud.githubusercontent.com/assets/1666536/12278706/c1055bf6-b982-11e5-8240-a8ae93af9513.png)
![screenshot_2016-01-12-23-16-44](https://cloud.githubusercontent.com/assets/1666536/12278708/c70bfc94-b982-11e5-93e9-daf5ec16f421.png)

Am I doing something wrong, can you help? Thanks

**Comment by C3C0** [comment]
Status bar tweaks in GravityBox are designed for devices with standard status bar located at the top of the screen. While some features may work also for bottom status bar, it is not guaranteed all of them will do. Support for bottom layout has been completely dropped by Google in later versions of Android.
I'm sorry but I don't have such device which could allow me to test or adjust related features. Moreover, I'm sorry to say I am not actively working on JellyBean branch anymore due to lack of time and the fact this Android version is quite outdated. Thanks for understanding.

**Comment by roughnecks** [comment]
Thank you; not a problem, I understand.
