### ISSUE TITLE
Nothing is being blocked by UNC on lock screen

### ISSUE THREAD

**Issue by code-issues-pull** [GravityBox/GravityBox#1504]
Android 5.1.1 (N6 so its stock android)
GB 5.3.7

Go into UNC, go to per app section, filter to show active items (irrelevant to the bug but helps speed up things), choose anything from the list and enable it. Go into it's settings and down to VISIBILITY, choose "Hide notification", Save. Reboot just to be sure (makes no difference). And voila! Nothing is hidden from lock screen.

This is happening for persistent notifications and temporary ones. Afwall, tasker, qksms, etc. In fact I haven't found an app it does hide notifications for. This bug has been around for at least the last 2-3 updates, if not longer.

**Comment by C3C0** [comment]
This feature is an extension to Android's "Hide notification content" on secured lock screen and it requires lock screen security and this feature to be turned on otherwise it has no effect. Option description says:
"Specifies notification visibility in **secured** lock screen. Applies when "**Hide sensitive notification content**" lock screen policy is active"
