### ISSUE TITLE
[Feature Request] Lockscreen: add option to treat "backspace" presses as failed attempts

### ISSUE THREAD

**Issue by c89williams** [GravityBox/GravityBox#1505]
The idea is that when the user presses the "backspace" button on the lockscreen PIN / password screen, it will count as a failed attempt.

This would only happen if there has been some interaction that could cause PIN / password input to progress. For example tapping backspace when nothing is entered does not trigger a failed attempt. Tapping backspace after entering any amount of numbers will count as 1 attempt, even when backspacing all the numbers.

This is mostly related to the "Quick unlock" option that will unlock the lockscreen as soon as the correct PIN is entered. It has no security whatsoever, the user could brute-force the PIN with no timeouts / delays by simply using backspace.

**Comment by c89williams** [comment]
Additionally, I can see in ModLockscreen.java that Quick Unlock will only check if the input length matches what is saved. It would not be desirable to trigger an "invalid attempt" when the length is reached but the input is wrong as the adversary would now know the length of the PIN / password.

**Comment by C3C0** [comment]
This feature had to be reworked for Marshmallow compatibility due to some essential changes in how Android's gatekeeper works. With changes you suggested we would be facing the same issues as we had before. Gatekeeper takes care of blocking the user after failed attempt for number of seconds that's increasing with number of failed attempts which prevents brute-forcing natively, making your suggestion obsolete.

Here are the relevant commits that were needed for marshmallow, for your reference:
https://github.com/GravityBox/GravityBox/commit/9fbb4012e6a68926e91a9b4f28c5aa1dc8ad0430
https://github.com/GravityBox/GravityBox/commit/2c0dfccebe5dc6da337f859c2843396aabb6a8e3
