### ISSUE TITLE
IR blaster stops working

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1521]
The phone is the Leeco 1s (x500), after some test i concluded that Gravitybox stopped the remote control app from working, it makes it crash. This module is the only I can activate my soft keys. qemu.hw.mainkeys=0 does not work in the build.prop

**Comment by C3C0** [comment]
I highly doubt GravityBox is a culprit as it doesn't touch 3rd party apps at all. It's designed for system level tweaks only. Anyway, we can only guess until logcat of crash is provided.

**Comment by ghost** [comment]
I am unsure how to make a proper logcat. I made one and searched for the name of the app. If this is not good please just say how I need to make it. http://pastebin.com/rcn7Ng0j

**Comment by C3C0** [comment]
This seems to be related part:
04-04 07:18:44.649 E/AndroidRuntime(11946): Process: com.letv.android.remotecontrol, PID: 11946
04-04 07:18:44.649 E/AndroidRuntime(11946): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.letv.android.remotecontrol/com.letv.android.remotecontrol.activity.AllDeviceListActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d01b5
04-04 07:18:44.649 E/AndroidRuntime(11946):     at com.letv.android.remotecontrol.utils.TabColorUtil.updateColor(TabColorUtil.java:34)
04-04 07:18:44.649 E/AndroidRuntime(11946):     at com.letv.android.remotecontrol.activity.AllDeviceListActivity.initTab(AllDeviceListActivity.java:295)
04-04 07:18:44.649 E/AndroidRuntime(11946):     at com.letv.android.remotecontrol.activity.AllDeviceListActivity.initViews(AllDeviceListActivity.java:260)
04-04 07:18:44.649 E/AndroidRuntime(11946):     at com.letv.android.remotecontrol.activity.AllDeviceListActivity.init(AllDeviceListActivity.java:151)
04-04 07:18:44.649 E/AndroidRuntime(11946):     at com.letv.android.remotecontrol.activity.AllDeviceListActivity.initView(AllDeviceListActivity.java:508)
04-04 07:18:44.649 E/AndroidRuntime(11946):     at com.letv.android.remotecontrol.activity.base.BaseUIActivity.onCreate(BaseUIActivity.java:44)

App is crashing due to not being able to get some resources. This is not GravityBox related. Might be related to xposed framework itself. You should test the app with all xposed modules disabled first. If it still crashes, you should uninstall xposed framework and test without it. Another alternative is to try "Disable resource hooks" option within Xposed Installer app. Note, that GravityBox won't work with this option enabled.

**Comment by ghost** [comment]
Tha app is working with all my xpose module. It stops when I activate gravity box and reboot.  This is why I find it strange.

**Comment by C3C0** [comment]
Then try to keep navbar tweaks disabled. Maybe your system has been stripped of some navigation bar related functionality and IR blaster app is not able to cope with that.

**Comment by ghost** [comment]
I tried clearing the data so nothing was activated but the remote control app stil didn't work. But it was more of a report. I can find some alternative since this bug porbabky only affect my phone and it is not very popular. But I really like controlling the brightness with the status bar but I will live without it.
