### ISSUE TITLE
Quick Settings Customs management 

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1572]
Whenever I restart the phone, many quick settings options are gone. That is only the custom quick settings appear. The defaults ones, like WiFi,  Bluetooth etc. don't. Need to go to the gravity box application to re-save it to work. Also, the ordering of the quick settings is not proper in the top row. Rather it is random. Sometimes, there'll be 3 and sometimes 2 settings in tge the top row. And this won't fix with the given option of "settings per row".

**Comment by C3C0** [comment]
Which device/ROM? GravityBox supports only AOSP systems (pure Android) plus recently there were some compatibility adjustments for Xperia devices regarding quick settings.

**Comment by ghost** [comment]
Stock Android on nexus 5. The issue is that the number od settings per row
doesn't work well.

**Comment by giiif** [comment]
Are you, by any change, using any other xposed modules that modify the quick settings? I have had a similar issue, and in my case it was caused by Android n-ify interfering with gravity box.

**Comment by C3C0** [comment]
Make sure to check how you have tiles ordered with regard to dual mode. Note, that QS by design does not support combination of standard tile and dual tile in one row. This means if you have order e.g. 1st tile normal, 2nd dual, 3rd normal, they all will be distributed throughout 3 rows. This is because 2nd dual tile cannot coexist with 1st and 2nd in one row. 

QS management is 100% OK on Nexus 5 running stock ROM. If it's not in your case I would start looking for other mods you might have on your device that could collide.

**Comment by Yakie996** [comment]
I have this issue too after I tried uit n-ify but I uninstalled it and the problem kept on existing, using moto x style stock ROM xt1572

https://goo.gl/photos/jL8YuwP3QxUb7qGQ7
