### ISSUE TITLE
QuickApp Tile Icons Are "Mysterious"

### ISSUE THREAD

**Issue by Unreasonable-User** [GravityBox/GravityBox#1753]
QuickApp tile icons are showing only a white filled outline for selected apps in Oreo beta2 and stable.
![beta2 stable](https://user-images.githubusercontent.com/36458737/36179439-eb3553c8-10e1-11e8-9c53-474b9495479c.png)

Oreo beta1 displayed the actual icon of the selected app.
![beta1](https://user-images.githubusercontent.com/36458737/36179476-0ede8baa-10e2-11e8-8c63-af93fd5ab848.png)

The beta1 behavior is much more clear and prevents situations where apps with the same icon shape (every app that follows android style guidelines) from becoming indistinguishable.
![quickapps](https://user-images.githubusercontent.com/36458737/36179612-939b27ea-10e2-11e8-9536-84ef9bbae1f3.png)

This only affects short press icons. Long press still displays colored app icons.

Please revert to beta1 display behavior.

**Comment by C3C0** [comment]
OS does its own tinting which makes original icons look like that. Use alternate icons from the predefined list of icons, which are suitable for tinting (alternate list of icons shows on short press on icon in the settings). Btw, what device/OS is this?

**Comment by Unreasonable-User** [comment]
Pixel XL, 8.1 w/ Feb sec update, magisk root, xposed beta3.

The OS applying tinting doesn't make sense to me because I took all those screens without changing anything other than the GB version. And GB was the only module I had activated while I was testing. That implies the behavior is due to a change in GB.

If reversion to beta1 behavior isn't possible, would you consider pulling in some more icons to pick from, maybe just settings type stuff from [material.io](https://material.io/icons/.) ([git](https://github.com/google/material-design-icons/))?

**Comment by C3C0** [comment]
You can use your own by long-pressing on an icon

**Comment by C3C0** [comment]
Tinting is done by QS panel based on tile state (active/inactive/disabled) and in beta1 I was doing explicit tinting myself because of different approach I had for handling protected tile appearance when Locked style was set to "Dimmed". Below is the version where I put back one part from beta1 that removes native tinting before I was applying mine. Please test and report back. Note, that icons will still not be OK right after boot, before unlocking or pulling QS panel down at least once. But this anomaly was the same in beta1.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Oreo_8.0.0_180214.apk

**Comment by Unreasonable-User** [comment]
That does the trick. Colors! Disambiguity!
![qa](https://user-images.githubusercontent.com/36458737/36237669-e8b6b998-11c2-11e8-966f-0c3d9c902c9f.png)

Thanks! I like this.
