### ISSUE TITLE
[Feature Request][P] On/Off Icons for Stay Awake QS Tile

### ISSUE THREAD

**Issue by creeve4** [GravityBox/GravityBox#1992]
It would be nice to have different icons for On and Off states.
On = NEVER_SLEEP
Off = any other timeout

**Comment by C3C0** [comment]
I agree. The thing is I am not that good at graphics and I always struggle when I need to create something. Especially when it's in a vector format. Here is the current icon: https://github.com/GravityBox/GravityBox/blob/pie/GravityBox/src/main/res/drawable/ic_qs_stayawake_on.xml
So if you have some skills you can let your creativity go :) Otherwise I will have to fight with Inscape once again.

**Comment by creeve4** [comment]
I'll take a crack at it. I might as well learn how to create and edit vector drawables.

Where in your code are you indicating the state of the QS tile (active or inactive)?

I was thinking that all states which have a time (15s, 30s, 1min, etc) the tile is inactive (color is gray) and only the stay awake state is active.

**Comment by C3C0** [comment]
For this suggested functionality it is not necessary to provide additional images. On/off state of tile can be controlled in handleUpdateState method of each tile. If mState.booleanValue is set to true (which is default) system renders icon as active. When false it renders it inactive. It uses the same white image which gets tinted accordingly.

**Comment by C3C0** [comment]
What about something like this. The icon would be for NEVER_SLEEP mode. Strike over the timer would mean screen off timer is not in effect.
![image](https://user-images.githubusercontent.com/1543473/59330448-c7e21400-8cf1-11e9-9c2e-440a5ccc87b2.png)

**Comment by C3C0** [comment]
And here is how it would look like.
![qs_stay_awake](https://user-images.githubusercontent.com/1543473/59332328-3e811080-8cf6-11e9-85c4-56d7061f7ccf.png)

**Comment by creeve4** [comment]
Perfect! I like it!
