### ISSUE TITLE
SystemUI crashing.

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#2038]
Hey Im getting systemui crashing on Android Q, Xiaomi Mi A1, EdXposed-YAHFA-v0.4.6.0_beta.4471.-release.

[logcat.txt](https://github.com/GravityBox/GravityBox/files/3828895/logcat.txt)

**Comment by C3C0** [comment]
Doen's seem to be related to GravityBox
`11-10 20:24:48.515  4348  4348 E AndroidRuntime: FATAL EXCEPTION: main
11-10 20:24:48.515  4348  4348 E AndroidRuntime: Process: com.android.systemui, PID: 4348
11-10 20:24:48.515  4348  4348 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.RINGER_MODE_CHANGED flg=0x34000010 (has extras) } in com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6@df20ee5
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.android.systemui.statusbar.policy.NetworkTraffic cannot be cast to com.android.systemui.statusbar.StatusBarIconView
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIcon(StatusBarIconController.java:363)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIconHolder(StatusBarIconController.java:370)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.lambda$handleSet$4(StatusBarIconControllerImpl.java:307)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.-$$Lambda$StatusBarIconControllerImpl$ayp5xWywAkBOOSd-6MshVHM8Mms.accept(Unknown Source:6)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at java.util.ArrayList.forEach(ArrayList.java:1262)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.handleSet(StatusBarIconControllerImpl.java:307)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.setIcon(StatusBarIconControllerImpl.java:165)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateAlarm(PhoneStatusBarPolicy.java:300)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateVolumeZen(PhoneStatusBarPolicy.java:422)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.access$900(PhoneStatusBarPolicy.java:84)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6.onReceive(PhoneStatusBarPolicy.java:764)
11-10 20:24:48.515  4348  4348 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)`

Looks like there is some kind of NetworkTraffic status bar element which causes the issue. Isn't it something you modded additionally? If not it's a ROM bug.

**Comment by ghost** [comment]
Okey thank you.
